final_project_laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route profile
Route::resource('profile', 'ProfileController');
Route::get('/explore', 'ProfileController@explore');
Route::get('/explore/{id}/follow', 'ProfileController@follow');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'PostController@index');


// route posts
Route::get('/', function(){
    return view('welcome');
});

Route::resource('posts', 'PostController');

Route::resource('comments', 'CommentController');

Route::get('/my_post', 'PostController@my_post')->name('posts.my_post');

Route::get('/my_comment', 'CommentController@my_comment')->name('comments.my_comment');


//like posts
Route::resource('postlike', 'PostLikeController');

//like comment
Route::resource('commentlike', 'CommentLikeController');

Route::get('/erd', function(){
    return view('layout.erd');
});

final_project_laravel/app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $table = 'posts';
    protected $guarded = [];

    public function author(){
        return $this->belongsTo('App\User', 'user_id');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }

    public function post_likes(){
        return $this->hasMany('App\LikePost');
    }

}

final_project_laravel/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;
use Auth;
use Storage;
use RealRashid\SweetAlert\Facades\Alert;

class PostController extends Controller
{
    //

    public function __construct(){
        $this->middleware('auth');
    }

    public function index(){
        $data = Post::all();
        $liked_posts = [];
        $liked_comments = [];

        // like posts
        foreach($data as $d){
            foreach($d->post_likes as $like){
                if($like->user_id == Auth::id()){{
                    $liked_posts[] = $d->id;
                }}
            }
        }

        // comment posts
        foreach($data as $d){
            foreach($d->comments as $comment){
                foreach($comment->comment_likes as $like){
                    if($like->user_id == Auth::id()){{
                        $liked_comments[] = $comment->id;
                    }}
                }
            }
        }

        return view('post.post-list', compact('data', 'liked_posts', 'liked_comments'));
    }

    public function create(){
        return view('post.create-post');
    }

    public function store(Request $request){

        $data = new Post;

        if($request->hasFile('photo')){
            $filename = $request["photo"]->getClientOriginalName();

            if( $data->photo ){
                Storage::delete('/public/posts/'.Auth::user()->profile->photo);
            }
            $request["photo"]->storeAs('posts', $filename, 'public');
        }else{
            $filename=$data->photo;
        }
        
        $data->title = $request['title'];
        $data->content = $request['content'];
        $data->photo = $filename;
        $data->user_id = Auth::id();
        $data->save();

        Alert::success('Berhasil!', 'Post baru berhasil ditambahkan!');

        return redirect('/posts');
        // ->with('success', 'Post baru berhasil ditambahkan!');
    }

    public function my_post(){
        $post = new Post;
        $user_id = Auth::id();
        $data = $post->where('user_id', $user_id)->get();
        return view('post.my-post', compact('data'));
    }

    // public function show($id){
    //     $data = Post::find($id);
    //     return view('post.my-post', compact('data'));
    // }

    public function edit($id){
        $data = Post::find($id);
        return view('post.edit-post', compact('data'));
    }

    public function update($id, Request $request){
        if($request->hasFile('photo')){
            $filename = $request["photo"]->getClientOriginalName();

            if( Post::find($id)->photo ){
                Storage::delete('/public/posts/'.Post::find($id)->photo);
            }
            $request["photo"]->storeAs('posts', $filename, 'public');
        }else{
            $filename=Post::find($id)->photo;
        }
        $data = Post::where('id', $id)->update([
            'title' => $request['title'],
            'content' => $request['content'],
            'photo' => $filename
        ]);

        Alert::success('Berhasil!', 'Post berhasil diperbaharui!');

        return redirect('/posts');
        // ->with('success', 'Data berhasil diperbaharui!');
    }

    public function destroy($id){
        $data = Post::find($id);
        $data->delete();

        Alert::success('Berhasil!', 'Post berhasil dihapus!');

        return redirect('/posts');
        // ->with('success', 'Data berhasil dihapus!');
    }
}

final_project_laravel/resources/views/post/create-post.blade.php
@extends('layout.master')
@section('content')
<div class="col-md mt-3">
    <form role="form" action="{{ route('posts.store', 'post') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Enter title">
            </div>

            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" class="form-control" rows="4" style="margin-top: 0px; margin-bottom: 0px; height: 110px;" placeholder="Enter text"></textarea>
            </div>

            <div class="form-group">
                <label for="photo">Photo</label>
                <input type="file" name="photo" id="photo">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
@endsection

final_project_laravel/resources/views/post/edit-post.blade.php
@extends('layout.master')
@section('content')
<div class="col-md mt-3">
    <form role="form" action="{{ route('posts.update', ['post' => $data->id]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Enter title" value="{{ $data->title }}">
            </div>

            <div class="form-group">
                <label for="content">Content</label>
                <textarea id="content" name="content" class="form-control" rows="4" style="margin-top: 0px; margin-bottom: 0px; height: 110px;" placeholder="Enter text">
                    {{ $data->content }}
                </textarea>
            </div>

            <div class="form-group">
                <label for="photo">Photo</label>
                <input type="file" name="photo" id="photo">
            </div>
        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
</div>
@endsection

final_project_laravel/resources/views/post/my-post.blade.php
@extends('layout.master')

@section('content')
<div class="col-md mt-3">

  @if(session('success'))
    <div class="alert alert-success">
      {{ session('success') }}
    </div>
  @endif

  <a href="{{ route('posts.create') }}" class="btn btn-block btn-success btn-lg mb-4">Buat Post Baru</a>
    <!-- Box Comment -->
    @foreach ($data as $key => $value)
    <div class="card card-widget">
      <div class="card-header">
        <div class="user-block">

          @if(Auth::user()->profile->photo)
            <img class="img-circle" src=" {{ asset('storage/photo/'.Auth::user()->profile->photo) }} " alt="User Avatar">
          @else
            <img class="img-circle" src="{{ asset('assets/dist/img/avatar.png') }}" alt="User Avatar">
          @endif
          
          <span class="username"><a href="#">{{ $value->author->name }}</a></span>
          <span class="description">Shared {{ $value->created_at }}</span>
          <span class="description">Last Edited {{ $value->updated_at }}</span>
        </div>
        <!-- /.user-block -->
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
            <i class="far fa-circle"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
          </button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">

        <!-- Attachment -->
        <div class="attachment-block clearfix">
          <div class="attachment-pushed">

            <div class="attachment-text">
              {{ $value->title }}
            </div>
            <!-- /.attachment-text -->
          </div>
          <!-- /.attachment-pushed -->
        </div>
        <!-- /.attachment-block -->

        @if($value->photo)
            <img class="" src=" {{ asset('storage/posts/'.$value->photo) }} " width="300px" alt="Posts Photo">
        @endif

        <!-- post text -->
        <p>
          {{ $value->content }}
        </p>

        <!-- Social sharing buttons -->
        {{-- <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button> --}}
        <a href="{{ route('posts.edit', ['post' => $value->id ]) }}" class="btn btn-default btn-warning btn-sm">
          <i class="fas fa-pencil-alt"></i>
          Edit
        </a>
        <form action="{{route('posts.destroy', ['post' => $value->id ])}}" method="POST">
          @csrf
          @method('DELETE')
          <button type="submit" value="delete" class="btn btn-default btn-danger btn-sm">
            <i class="fas fa-trash"></i>
            Delete
          </button>
        </form>
        <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
        <span class="float-right text-muted">0 likes - {{ $value->comments->count() }} comments</span>
      </div>
      <!-- /.card-body -->
      
      @foreach ($value->comments as $comment)
      <!-- /.card-body -->
      <div class="card-footer card-comments">
        <div class="card-comment">
          <!-- User image -->
          @if($comment->user->profile->photo)
            <img class="img-circle img-sm" src="{{ asset('storage/photo/'.$comment->user->profile->photo) }}" alt="User Image">
          @else
            <img class="img-circle img-sm" src=" {{ asset('assets/dist/img/avatar.png') }} " alt="User Image">
          @endif
          <div class="comment-text">
            <span class="username">
              {{$comment->user->name}}
              <span class="text-muted float-right">{{ $comment->created_at }}</span>
            </span><!-- /.username -->
            {{$comment->content}}
          </div>
          
          <!-- /.comment-text -->
        </div>
        <form action="{{route('comments.destroy', ['comment' => $comment->id])}}" method="POST">
          @csrf
          @method("DELETE")
          <div class="delete-buton">
            <input type="submit" value="delete" class="btn btn-danger btn-sm">
          </div>
        </form>
        <!-- /.card-comment -->
      </div>
      @endforeach
      
    </div>    
    @endforeach
    
    <!-- /.card -->
</div>    
@endsection

final_project_laravel/resources/views/post/post-list.blade.php
@extends('layout.master')

@section('content')
<div class="col-md mt-3">

  @if(session('success'))
    <div class="alert alert-success">
      {{ session('success') }}
    </div>
  @endif

  <a href="{{ route('posts.create') }}" class="btn btn-block btn-success btn-lg mb-4">Buat Post Baru</a>
    <!-- Box Comment -->
    @foreach ($data as $key => $value)
    <div class="card card-widget">
      <div class="card-header">
        <div class="user-block">
          
          {{-- masih gagal bedain post user sama punya orang --}}
          @if(Auth::id() == $value->author->id)
            <img class="img-circle" src=" {{ asset('storage/photo/'.Auth::user()->profile->photo) }} " alt="User Image">
          @else
            <img class="img-circle" src="{{ asset('assets/dist/img/user1-128x128.jpg') }}" alt="User Image">
          @endif
          
          <span class="username"><a href="#">{{ $value->author->name }}</a></span>
          <span class="description">Shared {{ $value->created_at }}</span>
          <span class="description">Last Edited {{ $value->updated_at }}</span>
        </div>
        <!-- /.user-block -->
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
            <i class="far fa-circle"></i></button>
          <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
          </button>
          <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
          </button>
        </div>
        <!-- /.card-tools -->
      </div>
      <!-- /.card-header -->
      <div class="card-body">

        <!-- Attachment -->
        <div class="attachment-block clearfix">
          <div class="attachment-pushed">

            <div class="attachment-text">
              {{ $value->title }}
            </div>
            <!-- /.attachment-text -->
          </div>
          <!-- /.attachment-pushed -->
        </div>
        <!-- /.attachment-block -->

        @if($value->photo)
            <img class="" src=" {{ asset('storage/posts/'.$value->photo) }} " width="300px" alt="Posts Photo">
        @endif

        <!-- post text -->
        <p>
          {{ $value->content }}
        </p>

        <!-- Social sharing buttons -->
        {{-- <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button> --}}
          <form action="{{ route('postlike.update', ['postlike' => Auth::id()]) }}" method="POST">
            @csrf
            @method("PUT")
            <input type="hidden" name="post_id" value="{{$value->id}}">
            @if(in_array($value->id, $liked_posts))
              <button  class="btn btn-primary btn-sm" value="save" ><i class="far fa-thumbs-up"></i> Like</button>
            @else
              <button  class="btn btn-default btn-sm" value="save" ><i class="far fa-thumbs-up"></i> Like</button>
            @endif
        </form>
        <span class="float-right text-muted">{{ $value->post_likes->count() }} likes - {{ $value->comments->count() }} comments</span>
      </div>

      @foreach ($value->comments as $comment)
      <!-- /.card-body -->
      <div class="card-footer card-comments">
        <div class="card-comment">
          <!-- User image -->
          @if($comment->user->profile->photo)
            <img class="img-circle img-sm" src="{{ asset('storage/photo/'.$comment->user->profile->photo) }}" alt="User Image">
          @else
            <img class="img-circle img-sm" src=" {{ asset('assets/dist/img/user1-128x128.jpg') }} " alt="User Image">
          @endif
          <div class="comment-text">
            <span class="username">
              {{$comment->user->name}}
              <span class="text-muted float-right">{{ $comment->created_at }}</span>
            </span><!-- /.username -->
            {{$comment->content}}
            <form action="{{ route('commentlike.update', ['commentlike' => Auth::id()]) }}" method="POST">
                @csrf
                @method("PUT")
                <input type="hidden" name="comment_id" value="{{$comment->id}}">
                @if(in_array($comment->id, $liked_comments))
                  <button  class="btn btn-primary btn-sm" value="save" ><i class="far fa-thumbs-up"></i> Like</button>
                @else
                  <button  class="btn btn-default btn-sm" value="save" ><i class="far fa-thumbs-up"></i> Like</button>
                @endif
            </form>
            <span class="float-right text-muted">{{ $comment->comment_likes->count() }} likes</span>
          </div>
          
          <!-- /.comment-text -->
        </div>
        {{-- <form action="{{route('comments.destroy', ['comment' => $comment->id])}}" method="POST">
          @csrf
          @method("DELETE")
          <div class="delete-buton">
            <input type="submit" value="delete" class="btn btn-danger btn-sm">
          </div>
        </form> --}}
        <!-- /.card-comment -->
      </div>
      @endforeach

      <!-- /.card-footer -->
      <div class="card-footer">
        <form action="{{route('comments.store')}}" method="POST">
          @csrf
          @if(Auth::user()->profile->photo)
            <img class="img-fluid img-circle img-sm" src="{{ asset('storage/photo/'.Auth::user()->profile->photo) }}" alt="Avatar">
          @else
            <img class="img-fluid img-circle img-sm" src=" {{ asset('assets/dist/img/user4-128x128.jpg') }} " alt="Avatar">
          @endif
          <!-- .img-push is used to add margin to elements next to floating images -->
          <div class="img-push">
            <input type="hidden" name="post_id" value="{{ $value->id }}">
            <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment" name="comment">
          </div>
        </form>
      </div>
      <!-- /.card-footer -->
    </div>    
    @endforeach
    
    <!-- /.card -->
</div>    
@endsection