final_project_laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// route profile
Route::resource('profile', 'ProfileController');
Route::get('/explore', 'ProfileController@explore');
Route::get('/explore/{id}/follow', 'ProfileController@follow');

Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'PostController@index');


// route posts
Route::get('/', function(){
    return view('welcome');
});

Route::resource('posts', 'PostController');

Route::resource('comments', 'CommentController');

Route::get('/my_post', 'PostController@my_post')->name('posts.my_post');

Route::get('/my_comment', 'CommentController@my_comment')->name('comments.my_comment');


//like posts
Route::resource('postlike', 'PostLikeController');

//like comment
Route::resource('commentlike', 'CommentLikeController');

Route::get('/erd', function(){
    return view('layout.erd');
});

final_project_laravel/resources/views/layout/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{ route('posts.index') }}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Authentication Links -->
      <li class="nav-item">
        @guest
            <li class="nav-item">
                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
            </li>
            @if (Route::has('register'))
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                </li>
            @endif
        @else
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }} <span class="caret"></span>
                </a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                        onclick="event.preventDefault();
                                      document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </li>
        @endguest
      </li>
    </ul>
  </nav>

final_project_laravel/resources/views/layout/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="{{ asset('assets/dist/img/mediaLogo.png') }}"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Sosial Now</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          
          @if(Auth::user()->profile->photo)
            <img src=" {{ asset('storage/photo/'. Auth::user()->profile->photo) }}" class="img-circle elevation-2" alt="Avatar">
          @else
            <img src=" {{ asset('/assets/dist/img/avatar.png')}}" class="img-circle elevation-2" alt="Avatar">
          @endif

        </div>
        <div class="info">
          <a href="#" class="d-block">
            {{ Auth::user()->name }}
          </a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{ route('profile.index') }}" class="nav-link">
              <i class="nav-icon fas fa-user-circle"></i>
              <p>
                Akun
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/explore" class="nav-link">
              <i class="nav-icon fas fa-user-circle"></i>
              <p>
                Jelajahi
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('posts.index') }}" class="nav-link">
              <i class="nav-icon far fa-newspaper"></i>
              <p>
                Posting Baru
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="{{ route('posts.my_post') }}" class="nav-link">
              <i class="nav-icon far fa-newspaper"></i>
              <p>
                Postinganku
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="/erd" class="nav-link">
              <i class="nav-icon fas fa-address-card"></i>
              <p>
                About Us
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>